<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery-1.7.2.min.js"></script>
<%-- <script type="text/javascript" src="<%=request.getContextPath()%>/js/easyui/jquery.min.js"></script> --%>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/easyui/jquery.easyui.min.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery.cookie.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/changeEasyuiTheme.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/common.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/nobackspace.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/easyui/defaults.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/prompt/ymPrompt.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/formatutil.js"></script>
<link rel="stylesheet" id="skin" type="text/css" href="<%=request.getContextPath()%>/js/prompt/skin/ymPrompt.css" />
<!--[if lt IE 8 ]><srcipt src="js/json2.js"></script><![endif]-->
<link id="easyuiTheme" rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/js/easyui/themes/metro-gray/easyui.css">
<link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/js/easyui/themes/icon.css">
<link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/css/css.css">
<!-- <script type="text/javascript" src="<%=request.getContextPath()%>/js/norightbutton.js"></script> -->
<script type="text/javascript" src="<%=request.getContextPath()%>/js/dateutil.js"></script>