<link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/js/jqplot/jquery.jqplot.min.css">
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jqplot/excanvas.min.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jqplot/jquery.jqplot.min.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jqplot/plugins/jqplot.dateAxisRenderer.min.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jqplot/plugins/jqplot.cursor.min.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jqplot/plugins/jqplot.LogAxisRenderer.min.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jqplot/plugins/jqplot.barRenderer.min.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jqplot/plugins/jqplot.categoryAxisRenderer.min.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jqplot/plugins/jqplot.highlighter.min.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jqplot/plugins/jqplot.pointLabels.min.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jqplot.js"></script>