<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery-1.7.2.min.js" charset="utf-8"></script>
<%-- <script type="text/javascript" src="<%=request.getContextPath()%>/js/easyui/jquery.min.js"></script> --%>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/easyui/jquery.easyui.min.js" charset="utf-8"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery.cookie.js" charset="utf-8"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/changeEasyuiTheme.js" charset="utf-8"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/common.js" charset="utf-8"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/nobackspace.js" charset="utf-8"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/easyui/defaults.js" charset="utf-8"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/prompt/ymPrompt.js" charset="utf-8"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/formatutil.js" charset="utf-8"></script>
<script src="<%=request.getContextPath()%>/js/easyui/locale/easyui-lang-zh_CN.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" id="skin" type="text/css" href="<%=request.getContextPath()%>/js/prompt/skin/ymPrompt.css" />
<!--[if lt IE 8 ]><srcipt src="js/json2.js"></script><![endif]-->
<link id="easyuiTheme" rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/js/easyui/themes/metro-gray/easyui.css">
<link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/js/easyui/themes/icon.css">
<link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/css/css.css">
<!-- <script type="text/javascript" src="<%=request.getContextPath()%>/js/norightbutton.js" charset="utf-8"></script> -->
<script type="text/javascript" src="<%=request.getContextPath()%>/js/dateutil.js" charset="utf-8"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/kz.js" charset="utf-8"></script>