<link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/js/highChart/icon.css">
<link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/js/highChart/easyui.css">
<script type="text/javascript" src="<%=request.getContextPath()%>/js/highChart/jquery.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/highChart/highcharts.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/highChart/exporting.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/highChart/jquery.easyui.min.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/highChart/easyui-lang-zh_CN.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/highChart/Common.js"></script>
